/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.cool.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCoolDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(it.disim.univaq.xtext.cool.coolDsl.CoolDslPackage.eINSTANCE);
		return result;
	}
}
