/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.cool.ui;

import com.google.inject.Injector;
import it.disim.univaq.xtext.cool.ui.internal.CoolActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CoolDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CoolActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CoolActivator activator = CoolActivator.getInstance();
		return activator != null ? activator.getInjector(CoolActivator.IT_DISIM_UNIVAQ_XTEXT_COOL_COOLDSL) : null;
	}

}
