/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.cool


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CoolDslRuntimeModule extends AbstractCoolDslRuntimeModule {
}
