/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PmanagementUiModule extends AbstractPmanagementUiModule {

	public PmanagementUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
