/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import it.disim.univaq.xtext.processmanagement.ide.contentassist.antlr.internal.InternalPmanagementParser;
import it.disim.univaq.xtext.processmanagement.services.PmanagementGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class PmanagementParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PmanagementGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PmanagementGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getUserTypeAccess().getAlternatives(), "rule__UserType__Alternatives");
			builder.put(grammarAccess.getProcessStatusAccess().getAlternatives(), "rule__ProcessStatus__Alternatives");
			builder.put(grammarAccess.getActionTypeAccess().getAlternatives(), "rule__ActionType__Alternatives");
			builder.put(grammarAccess.getActionStatusAccess().getAlternatives(), "rule__ActionStatus__Alternatives");
			builder.put(grammarAccess.getApplicationAccess().getGroup(), "rule__Application__Group__0");
			builder.put(grammarAccess.getApplicationAccess().getGroup_5(), "rule__Application__Group_5__0");
			builder.put(grammarAccess.getUserAccess().getGroup(), "rule__User__Group__0");
			builder.put(grammarAccess.getUserAccess().getGroup_3(), "rule__User__Group_3__0");
			builder.put(grammarAccess.getUserAccess().getGroup_8(), "rule__User__Group_8__0");
			builder.put(grammarAccess.getUserAccess().getGroup_11(), "rule__User__Group_11__0");
			builder.put(grammarAccess.getUserAccess().getGroup_12(), "rule__User__Group_12__0");
			builder.put(grammarAccess.getUserAccess().getGroup_12_3(), "rule__User__Group_12_3__0");
			builder.put(grammarAccess.getUserAccess().getGroup_13(), "rule__User__Group_13__0");
			builder.put(grammarAccess.getUserAccess().getGroup_13_3(), "rule__User__Group_13_3__0");
			builder.put(grammarAccess.getUserAccess().getGroup_14(), "rule__User__Group_14__0");
			builder.put(grammarAccess.getUserAccess().getGroup_14_3(), "rule__User__Group_14_3__0");
			builder.put(grammarAccess.getUserAccess().getGroup_15(), "rule__User__Group_15__0");
			builder.put(grammarAccess.getUserAccess().getGroup_15_3(), "rule__User__Group_15_3__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup(), "rule__Solution__Group__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup_3(), "rule__Solution__Group_3__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup_4(), "rule__Solution__Group_4__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup_8(), "rule__Solution__Group_8__0");
			builder.put(grammarAccess.getProblemAccess().getGroup(), "rule__Problem__Group__0");
			builder.put(grammarAccess.getProblemAccess().getGroup_3(), "rule__Problem__Group_3__0");
			builder.put(grammarAccess.getProblemAccess().getGroup_6(), "rule__Problem__Group_6__0");
			builder.put(grammarAccess.getProblemAccess().getGroup_6_3(), "rule__Problem__Group_6_3__0");
			builder.put(grammarAccess.getProblemAccess().getGroup_7(), "rule__Problem__Group_7__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup(), "rule__ItemProcess__Group__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup_3(), "rule__ItemProcess__Group_3__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup_6(), "rule__ItemProcess__Group_6__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup_7(), "rule__ItemProcess__Group_7__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup_7_3(), "rule__ItemProcess__Group_7_3__0");
			builder.put(grammarAccess.getProcessAccess().getGroup(), "rule__Process__Group__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_3(), "rule__Process__Group_3__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_4(), "rule__Process__Group_4__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_11(), "rule__Process__Group_11__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_12(), "rule__Process__Group_12__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_13(), "rule__Process__Group_13__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_13_3(), "rule__Process__Group_13_3__0");
			builder.put(grammarAccess.getItemSpeciesAccess().getGroup(), "rule__ItemSpecies__Group__0");
			builder.put(grammarAccess.getItemSpeciesAccess().getGroup_4(), "rule__ItemSpecies__Group_4__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getLocationAccess().getGroup_4(), "rule__Location__Group_4__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_3(), "rule__Action__Group_3__0");
			builder.put(grammarAccess.getActionAccess().getGroup_8(), "rule__Action__Group_8__0");
			builder.put(grammarAccess.getActionAccess().getGroup_11(), "rule__Action__Group_11__0");
			builder.put(grammarAccess.getActionAccess().getGroup_12(), "rule__Action__Group_12__0");
			builder.put(grammarAccess.getApplicationAccess().getUserAssignment_4(), "rule__Application__UserAssignment_4");
			builder.put(grammarAccess.getApplicationAccess().getUserAssignment_5_1(), "rule__Application__UserAssignment_5_1");
			builder.put(grammarAccess.getUserAccess().getNameAssignment_1(), "rule__User__NameAssignment_1");
			builder.put(grammarAccess.getUserAccess().getDescriptionAssignment_3_1(), "rule__User__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getUserAccess().getEmailAssignment_5(), "rule__User__EmailAssignment_5");
			builder.put(grammarAccess.getUserAccess().getUsernameAssignment_7(), "rule__User__UsernameAssignment_7");
			builder.put(grammarAccess.getUserAccess().getSurnameAssignment_8_1(), "rule__User__SurnameAssignment_8_1");
			builder.put(grammarAccess.getUserAccess().getUserTypeAssignment_10(), "rule__User__UserTypeAssignment_10");
			builder.put(grammarAccess.getUserAccess().getBirthdateAssignment_11_1(), "rule__User__BirthdateAssignment_11_1");
			builder.put(grammarAccess.getUserAccess().getSolutionsAssignment_12_2(), "rule__User__SolutionsAssignment_12_2");
			builder.put(grammarAccess.getUserAccess().getSolutionsAssignment_12_3_1(), "rule__User__SolutionsAssignment_12_3_1");
			builder.put(grammarAccess.getUserAccess().getProblemsAssignment_13_2(), "rule__User__ProblemsAssignment_13_2");
			builder.put(grammarAccess.getUserAccess().getProblemsAssignment_13_3_1(), "rule__User__ProblemsAssignment_13_3_1");
			builder.put(grammarAccess.getUserAccess().getItemProcessAssignment_14_2(), "rule__User__ItemProcessAssignment_14_2");
			builder.put(grammarAccess.getUserAccess().getItemProcessAssignment_14_3_1(), "rule__User__ItemProcessAssignment_14_3_1");
			builder.put(grammarAccess.getUserAccess().getProcessAssignment_15_2(), "rule__User__ProcessAssignment_15_2");
			builder.put(grammarAccess.getUserAccess().getProcessAssignment_15_3_1(), "rule__User__ProcessAssignment_15_3_1");
			builder.put(grammarAccess.getSolutionAccess().getNameAssignment_1(), "rule__Solution__NameAssignment_1");
			builder.put(grammarAccess.getSolutionAccess().getDescriptionAssignment_3_1(), "rule__Solution__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getSolutionAccess().getAuthorAssignment_4_1(), "rule__Solution__AuthorAssignment_4_1");
			builder.put(grammarAccess.getSolutionAccess().getProblemsAssignment_7(), "rule__Solution__ProblemsAssignment_7");
			builder.put(grammarAccess.getSolutionAccess().getProblemsAssignment_8_1(), "rule__Solution__ProblemsAssignment_8_1");
			builder.put(grammarAccess.getProblemAccess().getNameAssignment_1(), "rule__Problem__NameAssignment_1");
			builder.put(grammarAccess.getProblemAccess().getDescriptionAssignment_3_1(), "rule__Problem__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getProblemAccess().getAuthorAssignment_5(), "rule__Problem__AuthorAssignment_5");
			builder.put(grammarAccess.getProblemAccess().getSolutionsAssignment_6_2(), "rule__Problem__SolutionsAssignment_6_2");
			builder.put(grammarAccess.getProblemAccess().getSolutionsAssignment_6_3_1(), "rule__Problem__SolutionsAssignment_6_3_1");
			builder.put(grammarAccess.getProblemAccess().getProcessAssignment_7_1(), "rule__Problem__ProcessAssignment_7_1");
			builder.put(grammarAccess.getItemProcessAccess().getNameAssignment_1(), "rule__ItemProcess__NameAssignment_1");
			builder.put(grammarAccess.getItemProcessAccess().getDescriptionAssignment_3_1(), "rule__ItemProcess__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getItemProcessAccess().getAuthorAssignment_5(), "rule__ItemProcess__AuthorAssignment_5");
			builder.put(grammarAccess.getItemProcessAccess().getItemProcessTypeAssignment_6_1(), "rule__ItemProcess__ItemProcessTypeAssignment_6_1");
			builder.put(grammarAccess.getItemProcessAccess().getProblemsAssignment_7_2(), "rule__ItemProcess__ProblemsAssignment_7_2");
			builder.put(grammarAccess.getItemProcessAccess().getProblemsAssignment_7_3_1(), "rule__ItemProcess__ProblemsAssignment_7_3_1");
			builder.put(grammarAccess.getProcessAccess().getNameAssignment_1(), "rule__Process__NameAssignment_1");
			builder.put(grammarAccess.getProcessAccess().getDescriptionAssignment_3_1(), "rule__Process__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getProcessAccess().getStatusAssignment_4_1(), "rule__Process__StatusAssignment_4_1");
			builder.put(grammarAccess.getProcessAccess().getStartDateAssignment_6(), "rule__Process__StartDateAssignment_6");
			builder.put(grammarAccess.getProcessAccess().getEndDateAssignment_8(), "rule__Process__EndDateAssignment_8");
			builder.put(grammarAccess.getProcessAccess().getWeightAssignment_10(), "rule__Process__WeightAssignment_10");
			builder.put(grammarAccess.getProcessAccess().getItemProcessAssignment_11_1(), "rule__Process__ItemProcessAssignment_11_1");
			builder.put(grammarAccess.getProcessAccess().getLocationAssignment_12_1(), "rule__Process__LocationAssignment_12_1");
			builder.put(grammarAccess.getProcessAccess().getActionHistoryAssignment_13_2(), "rule__Process__ActionHistoryAssignment_13_2");
			builder.put(grammarAccess.getProcessAccess().getActionHistoryAssignment_13_3_1(), "rule__Process__ActionHistoryAssignment_13_3_1");
			builder.put(grammarAccess.getItemSpeciesAccess().getNameAssignment_2(), "rule__ItemSpecies__NameAssignment_2");
			builder.put(grammarAccess.getItemSpeciesAccess().getDescriptionAssignment_4_1(), "rule__ItemSpecies__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getLocationAccess().getNameAssignment_2(), "rule__Location__NameAssignment_2");
			builder.put(grammarAccess.getLocationAccess().getDescriptionAssignment_4_1(), "rule__Location__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
			builder.put(grammarAccess.getActionAccess().getDescriptionAssignment_3_1(), "rule__Action__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getActionAccess().getActionsTypeAssignment_5(), "rule__Action__ActionsTypeAssignment_5");
			builder.put(grammarAccess.getActionAccess().getActionStatusAssignment_7(), "rule__Action__ActionStatusAssignment_7");
			builder.put(grammarAccess.getActionAccess().getStartDateAssignment_8_1(), "rule__Action__StartDateAssignment_8_1");
			builder.put(grammarAccess.getActionAccess().getEndDateAssignment_10(), "rule__Action__EndDateAssignment_10");
			builder.put(grammarAccess.getActionAccess().getProblemAssignment_11_1(), "rule__Action__ProblemAssignment_11_1");
			builder.put(grammarAccess.getActionAccess().getSolutionAssignment_12_1(), "rule__Action__SolutionAssignment_12_1");
			builder.put(grammarAccess.getActionAccess().getProcessAssignment_14(), "rule__Action__ProcessAssignment_14");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PmanagementGrammarAccess grammarAccess;

	@Override
	protected InternalPmanagementParser createParser() {
		InternalPmanagementParser result = new InternalPmanagementParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PmanagementGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PmanagementGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
