/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.ui;

import com.google.inject.Injector;
import it.disim.univaq.xtextC.ui.internal.XtextCActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CoolExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(XtextCActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		XtextCActivator activator = XtextCActivator.getInstance();
		return activator != null ? activator.getInjector(XtextCActivator.IT_DISIM_UNIVAQ_XTEXT_COOL) : null;
	}

}
