/**
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.cool;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CoolDslStandaloneSetup extends CoolDslStandaloneSetupGenerated {
  public static void doSetup() {
    new CoolDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
