/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement.ide;


/**
 * Use this class to register ide components.
 */
public class PmanagementIdeModule extends AbstractPmanagementIdeModule {
}
