/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.disim.univaq.xtext.processmanagement.PmanagementRuntimeModule;
import it.disim.univaq.xtext.processmanagement.PmanagementStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PmanagementIdeSetup extends PmanagementStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PmanagementRuntimeModule(), new PmanagementIdeModule()));
	}
	
}
