/**
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement.formatting2;

import com.google.inject.Inject;
import it.disim.univaq.porcessmanagement.Application;
import it.disim.univaq.porcessmanagement.ItemProcess;
import it.disim.univaq.porcessmanagement.Problem;
import it.disim.univaq.porcessmanagement.Solution;
import it.disim.univaq.porcessmanagement.User;
import it.disim.univaq.xtext.processmanagement.services.PmanagementGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class PmanagementFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private PmanagementGrammarAccess _pmanagementGrammarAccess;
  
  protected void _format(final Application application, @Extension final IFormattableDocument document) {
    EList<User> _user = application.getUser();
    for (final User user : _user) {
      document.<User>format(user);
    }
  }
  
  protected void _format(final User user, @Extension final IFormattableDocument document) {
    EList<Solution> _solutions = user.getSolutions();
    for (final Solution solution : _solutions) {
      document.<Solution>format(solution);
    }
    EList<Problem> _problems = user.getProblems();
    for (final Problem problem : _problems) {
      document.<Problem>format(problem);
    }
    EList<ItemProcess> _itemProcess = user.getItemProcess();
    for (final ItemProcess itemProcess : _itemProcess) {
      document.<ItemProcess>format(itemProcess);
    }
    EList<it.disim.univaq.porcessmanagement.Process> _process = user.getProcess();
    for (final it.disim.univaq.porcessmanagement.Process process : _process) {
      document.<it.disim.univaq.porcessmanagement.Process>format(process);
    }
  }
  
  public void format(final Object user, final IFormattableDocument document) {
    if (user instanceof XtextResource) {
      _format((XtextResource)user, document);
      return;
    } else if (user instanceof User) {
      _format((User)user, document);
      return;
    } else if (user instanceof Application) {
      _format((Application)user, document);
      return;
    } else if (user instanceof EObject) {
      _format((EObject)user, document);
      return;
    } else if (user == null) {
      _format((Void)null, document);
      return;
    } else if (user != null) {
      _format(user, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(user, document).toString());
    }
  }
}
