/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PmanagementStandaloneSetup extends PmanagementStandaloneSetupGenerated {

	public static void doSetup() {
		new PmanagementStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
