/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement.ui;

import com.google.inject.Injector;
import it.disim.univaq.xtext.processmanagement.ui.internal.ProcessmanagementActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PmanagementExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ProcessmanagementActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ProcessmanagementActivator activator = ProcessmanagementActivator.getInstance();
		return activator != null ? activator.getInjector(ProcessmanagementActivator.IT_DISIM_UNIVAQ_XTEXT_PROCESSMANAGEMENT_PMANAGEMENT) : null;
	}

}
