/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.parser.antlr;

import com.google.inject.Inject;
import it.disim.univaq.xtext.parser.antlr.internal.InternalCoolParser;
import it.disim.univaq.xtext.services.CoolGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CoolParser extends AbstractAntlrParser {

	@Inject
	private CoolGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCoolParser createParser(XtextTokenStream stream) {
		return new InternalCoolParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Application";
	}

	public CoolGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CoolGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
