package ProML.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Process_Constraints extends BaseConstraintsDescriptor {
  public Process_Constraints() {
    super(CONCEPTS.Process$2x);
  }

  public static class Weight_Property extends BasePropertyConstraintsDescriptor {
    public Weight_Property(ConstraintsDescriptor container) {
      super(PROPS.weight$6DCw, container);
    }
    @Override
    public boolean hasOwnValidator() {
      return true;
    }
    private static final SNodePointer validatePropertyBreakingPoint = new SNodePointer("r:5f77f3d9-8f47-450f-ba5a-0eba7bc129ab(ProML.constraints)", "2708398504493682347");
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(validatePropertyBreakingPoint);
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue > 0;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.weight$6DCw, new Weight_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Process$2x = MetaAdapterFactory.getConcept(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d34L, "ProML.structure.Process");
  }

  private static final class PROPS {
    /*package*/ static final SProperty weight$6DCw = MetaAdapterFactory.getProperty(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d34L, 0x25962a171285b310L, "weight");
  }
}
