/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.serializer;

import com.google.inject.Inject;
import it.disim.univaq.xtext.services.CoolGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class CoolSyntacticSequencer extends AbstractSyntacticSequencer {

	protected CoolGrammarAccess grammarAccess;
	protected AbstractElementAlias match_User___ItemProcessKeyword_16_0_LeftCurlyBracketKeyword_16_1_RightCurlyBracketKeyword_16_4__q;
	protected AbstractElementAlias match_User___ProblemsKeyword_15_0_LeftCurlyBracketKeyword_15_1_RightCurlyBracketKeyword_15_4__q;
	protected AbstractElementAlias match_User___ProcessKeyword_17_0_LeftCurlyBracketKeyword_17_1_RightCurlyBracketKeyword_17_4__q;
	protected AbstractElementAlias match_User___SolutionsKeyword_14_0_LeftCurlyBracketKeyword_14_1_RightCurlyBracketKeyword_14_4__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (CoolGrammarAccess) access;
		match_User___ItemProcessKeyword_16_0_LeftCurlyBracketKeyword_16_1_RightCurlyBracketKeyword_16_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUserAccess().getItemProcessKeyword_16_0()), new TokenAlias(false, false, grammarAccess.getUserAccess().getLeftCurlyBracketKeyword_16_1()), new TokenAlias(false, false, grammarAccess.getUserAccess().getRightCurlyBracketKeyword_16_4()));
		match_User___ProblemsKeyword_15_0_LeftCurlyBracketKeyword_15_1_RightCurlyBracketKeyword_15_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUserAccess().getProblemsKeyword_15_0()), new TokenAlias(false, false, grammarAccess.getUserAccess().getLeftCurlyBracketKeyword_15_1()), new TokenAlias(false, false, grammarAccess.getUserAccess().getRightCurlyBracketKeyword_15_4()));
		match_User___ProcessKeyword_17_0_LeftCurlyBracketKeyword_17_1_RightCurlyBracketKeyword_17_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUserAccess().getProcessKeyword_17_0()), new TokenAlias(false, false, grammarAccess.getUserAccess().getLeftCurlyBracketKeyword_17_1()), new TokenAlias(false, false, grammarAccess.getUserAccess().getRightCurlyBracketKeyword_17_4()));
		match_User___SolutionsKeyword_14_0_LeftCurlyBracketKeyword_14_1_RightCurlyBracketKeyword_14_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUserAccess().getSolutionsKeyword_14_0()), new TokenAlias(false, false, grammarAccess.getUserAccess().getLeftCurlyBracketKeyword_14_1()), new TokenAlias(false, false, grammarAccess.getUserAccess().getRightCurlyBracketKeyword_14_4()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_User___ItemProcessKeyword_16_0_LeftCurlyBracketKeyword_16_1_RightCurlyBracketKeyword_16_4__q.equals(syntax))
				emit_User___ItemProcessKeyword_16_0_LeftCurlyBracketKeyword_16_1_RightCurlyBracketKeyword_16_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_User___ProblemsKeyword_15_0_LeftCurlyBracketKeyword_15_1_RightCurlyBracketKeyword_15_4__q.equals(syntax))
				emit_User___ProblemsKeyword_15_0_LeftCurlyBracketKeyword_15_1_RightCurlyBracketKeyword_15_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_User___ProcessKeyword_17_0_LeftCurlyBracketKeyword_17_1_RightCurlyBracketKeyword_17_4__q.equals(syntax))
				emit_User___ProcessKeyword_17_0_LeftCurlyBracketKeyword_17_1_RightCurlyBracketKeyword_17_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_User___SolutionsKeyword_14_0_LeftCurlyBracketKeyword_14_1_RightCurlyBracketKeyword_14_4__q.equals(syntax))
				emit_User___SolutionsKeyword_14_0_LeftCurlyBracketKeyword_14_1_RightCurlyBracketKeyword_14_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('itemProcess' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     problems+=Problem '}' (ambiguity) 'process' '{' ',' process+=Process
	 *     problems+=Problem '}' (ambiguity) 'process' '{' process+=Process
	 *     problems+=Problem '}' (ambiguity) ('process' '{' '}')? '}' (rule end)
	 *     solutions+=Solution '}' ('problems' '{' '}')? (ambiguity) 'process' '{' ',' process+=Process
	 *     solutions+=Solution '}' ('problems' '{' '}')? (ambiguity) 'process' '{' process+=Process
	 *     solutions+=Solution '}' ('problems' '{' '}')? (ambiguity) ('process' '{' '}')? '}' (rule end)
	 *     userType=UserType ('solutions' '{' '}')? ('problems' '{' '}')? (ambiguity) 'process' '{' ',' process+=Process
	 *     userType=UserType ('solutions' '{' '}')? ('problems' '{' '}')? (ambiguity) 'process' '{' process+=Process
	 *     userType=UserType ('solutions' '{' '}')? ('problems' '{' '}')? (ambiguity) ('process' '{' '}')? '}' (rule end)
	 */
	protected void emit_User___ItemProcessKeyword_16_0_LeftCurlyBracketKeyword_16_1_RightCurlyBracketKeyword_16_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('problems' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     solutions+=Solution '}' (ambiguity) 'itemProcess' '{' ',' itemProcess+=ItemProcess
	 *     solutions+=Solution '}' (ambiguity) 'itemProcess' '{' itemProcess+=ItemProcess
	 *     solutions+=Solution '}' (ambiguity) ('itemProcess' '{' '}')? 'process' '{' ',' process+=Process
	 *     solutions+=Solution '}' (ambiguity) ('itemProcess' '{' '}')? 'process' '{' process+=Process
	 *     solutions+=Solution '}' (ambiguity) ('itemProcess' '{' '}')? ('process' '{' '}')? '}' (rule end)
	 *     userType=UserType ('solutions' '{' '}')? (ambiguity) 'itemProcess' '{' ',' itemProcess+=ItemProcess
	 *     userType=UserType ('solutions' '{' '}')? (ambiguity) 'itemProcess' '{' itemProcess+=ItemProcess
	 *     userType=UserType ('solutions' '{' '}')? (ambiguity) ('itemProcess' '{' '}')? 'process' '{' ',' process+=Process
	 *     userType=UserType ('solutions' '{' '}')? (ambiguity) ('itemProcess' '{' '}')? 'process' '{' process+=Process
	 *     userType=UserType ('solutions' '{' '}')? (ambiguity) ('itemProcess' '{' '}')? ('process' '{' '}')? '}' (rule end)
	 */
	protected void emit_User___ProblemsKeyword_15_0_LeftCurlyBracketKeyword_15_1_RightCurlyBracketKeyword_15_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('process' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     itemProcess+=ItemProcess '}' (ambiguity) '}' (rule end)
	 *     problems+=Problem '}' ('itemProcess' '{' '}')? (ambiguity) '}' (rule end)
	 *     solutions+=Solution '}' ('problems' '{' '}')? ('itemProcess' '{' '}')? (ambiguity) '}' (rule end)
	 *     userType=UserType ('solutions' '{' '}')? ('problems' '{' '}')? ('itemProcess' '{' '}')? (ambiguity) '}' (rule end)
	 */
	protected void emit_User___ProcessKeyword_17_0_LeftCurlyBracketKeyword_17_1_RightCurlyBracketKeyword_17_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('solutions' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     userType=UserType (ambiguity) 'problems' '{' ',' problems+=Problem
	 *     userType=UserType (ambiguity) 'problems' '{' problems+=Problem
	 *     userType=UserType (ambiguity) ('problems' '{' '}')? 'itemProcess' '{' ',' itemProcess+=ItemProcess
	 *     userType=UserType (ambiguity) ('problems' '{' '}')? 'itemProcess' '{' itemProcess+=ItemProcess
	 *     userType=UserType (ambiguity) ('problems' '{' '}')? ('itemProcess' '{' '}')? 'process' '{' ',' process+=Process
	 *     userType=UserType (ambiguity) ('problems' '{' '}')? ('itemProcess' '{' '}')? 'process' '{' process+=Process
	 *     userType=UserType (ambiguity) ('problems' '{' '}')? ('itemProcess' '{' '}')? ('process' '{' '}')? '}' (rule end)
	 */
	protected void emit_User___SolutionsKeyword_14_0_LeftCurlyBracketKeyword_14_1_RightCurlyBracketKeyword_14_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
