/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.ui.tests;

import com.google.inject.Injector;
import it.disim.univaq.xtextC.ui.internal.XtextCActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CoolUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextCActivator.getInstance().getInjector("it.disim.univaq.xtext.Cool");
	}

}
