/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CoolStandaloneSetup extends CoolStandaloneSetupGenerated {

	public static void doSetup() {
		new CoolStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
