/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PmanagementAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/disim/univaq/xtext/processmanagement/parser/antlr/internal/InternalPmanagement.tokens");
	}
}
