/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CoolGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ApplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.Application");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cApplicationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cUserKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUserAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUserUserParserRuleCall_4_0 = (RuleCall)cUserAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cUserAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cUserUserParserRuleCall_5_1_0 = (RuleCall)cUserAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Application returns Application:
		//    'Application'
		//    '{'
		//        'user' '{' user+=User ( "," user+=User)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Application'
		//'{'
		//    'user' '{' user+=User ( "," user+=User)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Application'
		public Keyword getApplicationKeyword_0() { return cApplicationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'user'
		public Keyword getUserKeyword_2() { return cUserKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//user+=User
		public Assignment getUserAssignment_4() { return cUserAssignment_4; }
		
		//User
		public RuleCall getUserUserParserRuleCall_4_0() { return cUserUserParserRuleCall_4_0; }
		
		//( "," user+=User)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//user+=User
		public Assignment getUserAssignment_5_1() { return cUserAssignment_5_1; }
		
		//User
		public RuleCall getUserUserParserRuleCall_5_1_0() { return cUserUserParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class UserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.User");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUserKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cEmailKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cEmailAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cEmailEStringParserRuleCall_5_0 = (RuleCall)cEmailAssignment_5.eContents().get(0);
		private final Keyword cUsernameKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cUsernameAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cUsernameEStringParserRuleCall_7_0 = (RuleCall)cUsernameAssignment_7.eContents().get(0);
		private final Keyword cUnameKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cUnameAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cUnameEStringParserRuleCall_9_0 = (RuleCall)cUnameAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cBirthdateKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cBirthdateAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cBirthdateEDateParserRuleCall_10_1_0 = (RuleCall)cBirthdateAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cSurnameKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cSurnameAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cSurnameEStringParserRuleCall_11_1_0 = (RuleCall)cSurnameAssignment_11_1.eContents().get(0);
		private final Keyword cUserTypeKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cUserTypeAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cUserTypeUserTypeEnumRuleCall_13_0 = (RuleCall)cUserTypeAssignment_13.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cSolutionsKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Assignment cSolutionsAssignment_14_2 = (Assignment)cGroup_14.eContents().get(2);
		private final RuleCall cSolutionsSolutionParserRuleCall_14_2_0 = (RuleCall)cSolutionsAssignment_14_2.eContents().get(0);
		private final Group cGroup_14_3 = (Group)cGroup_14.eContents().get(3);
		private final Keyword cCommaKeyword_14_3_0 = (Keyword)cGroup_14_3.eContents().get(0);
		private final Assignment cSolutionsAssignment_14_3_1 = (Assignment)cGroup_14_3.eContents().get(1);
		private final RuleCall cSolutionsSolutionParserRuleCall_14_3_1_0 = (RuleCall)cSolutionsAssignment_14_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14_4 = (Keyword)cGroup_14.eContents().get(4);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cProblemsKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Assignment cProblemsAssignment_15_2 = (Assignment)cGroup_15.eContents().get(2);
		private final RuleCall cProblemsProblemParserRuleCall_15_2_0 = (RuleCall)cProblemsAssignment_15_2.eContents().get(0);
		private final Group cGroup_15_3 = (Group)cGroup_15.eContents().get(3);
		private final Keyword cCommaKeyword_15_3_0 = (Keyword)cGroup_15_3.eContents().get(0);
		private final Assignment cProblemsAssignment_15_3_1 = (Assignment)cGroup_15_3.eContents().get(1);
		private final RuleCall cProblemsProblemParserRuleCall_15_3_1_0 = (RuleCall)cProblemsAssignment_15_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15_4 = (Keyword)cGroup_15.eContents().get(4);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cItemProcessKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_16_1 = (Keyword)cGroup_16.eContents().get(1);
		private final Assignment cItemProcessAssignment_16_2 = (Assignment)cGroup_16.eContents().get(2);
		private final RuleCall cItemProcessItemProcessParserRuleCall_16_2_0 = (RuleCall)cItemProcessAssignment_16_2.eContents().get(0);
		private final Group cGroup_16_3 = (Group)cGroup_16.eContents().get(3);
		private final Keyword cCommaKeyword_16_3_0 = (Keyword)cGroup_16_3.eContents().get(0);
		private final Assignment cItemProcessAssignment_16_3_1 = (Assignment)cGroup_16_3.eContents().get(1);
		private final RuleCall cItemProcessItemProcessParserRuleCall_16_3_1_0 = (RuleCall)cItemProcessAssignment_16_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16_4 = (Keyword)cGroup_16.eContents().get(4);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cProcessKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_17_1 = (Keyword)cGroup_17.eContents().get(1);
		private final Assignment cProcessAssignment_17_2 = (Assignment)cGroup_17.eContents().get(2);
		private final RuleCall cProcessProcessParserRuleCall_17_2_0 = (RuleCall)cProcessAssignment_17_2.eContents().get(0);
		private final Group cGroup_17_3 = (Group)cGroup_17.eContents().get(3);
		private final Keyword cCommaKeyword_17_3_0 = (Keyword)cGroup_17_3.eContents().get(0);
		private final Assignment cProcessAssignment_17_3_1 = (Assignment)cGroup_17_3.eContents().get(1);
		private final RuleCall cProcessProcessParserRuleCall_17_3_1_0 = (RuleCall)cProcessAssignment_17_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17_4 = (Keyword)cGroup_17.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//User returns User:
		//    'User'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        'email' email=EString
		//        'username' username=EString
		//        'uname' uname=EString
		//        ('birthdate' birthdate=EDate)?
		//        ('surname' surname=EString)?
		//        'userType' userType=UserType
		//        ('solutions' '{' solutions+=Solution* ( "," solutions+=Solution)* '}' )?
		//        ('problems' '{' problems+=Problem* ( "," problems+=Problem)* '}' )?
		//        ('itemProcess' '{' itemProcess+=ItemProcess* ( "," itemProcess+=ItemProcess)* '}' )?
		//        ('process' '{' process+=Process* ( "," process+=Process)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'User'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    'email' email=EString
		//    'username' username=EString
		//    'uname' uname=EString
		//    ('birthdate' birthdate=EDate)?
		//    ('surname' surname=EString)?
		//    'userType' userType=UserType
		//    ('solutions' '{' solutions+=Solution* ( "," solutions+=Solution)* '}' )?
		//    ('problems' '{' problems+=Problem* ( "," problems+=Problem)* '}' )?
		//    ('itemProcess' '{' itemProcess+=ItemProcess* ( "," itemProcess+=ItemProcess)* '}' )?
		//    ('process' '{' process+=Process* ( "," process+=Process)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'User'
		public Keyword getUserKeyword_0() { return cUserKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description' description=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//'email'
		public Keyword getEmailKeyword_4() { return cEmailKeyword_4; }
		
		//email=EString
		public Assignment getEmailAssignment_5() { return cEmailAssignment_5; }
		
		//EString
		public RuleCall getEmailEStringParserRuleCall_5_0() { return cEmailEStringParserRuleCall_5_0; }
		
		//'username'
		public Keyword getUsernameKeyword_6() { return cUsernameKeyword_6; }
		
		//username=EString
		public Assignment getUsernameAssignment_7() { return cUsernameAssignment_7; }
		
		//EString
		public RuleCall getUsernameEStringParserRuleCall_7_0() { return cUsernameEStringParserRuleCall_7_0; }
		
		//'uname'
		public Keyword getUnameKeyword_8() { return cUnameKeyword_8; }
		
		//uname=EString
		public Assignment getUnameAssignment_9() { return cUnameAssignment_9; }
		
		//EString
		public RuleCall getUnameEStringParserRuleCall_9_0() { return cUnameEStringParserRuleCall_9_0; }
		
		//('birthdate' birthdate=EDate)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'birthdate'
		public Keyword getBirthdateKeyword_10_0() { return cBirthdateKeyword_10_0; }
		
		//birthdate=EDate
		public Assignment getBirthdateAssignment_10_1() { return cBirthdateAssignment_10_1; }
		
		//EDate
		public RuleCall getBirthdateEDateParserRuleCall_10_1_0() { return cBirthdateEDateParserRuleCall_10_1_0; }
		
		//('surname' surname=EString)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'surname'
		public Keyword getSurnameKeyword_11_0() { return cSurnameKeyword_11_0; }
		
		//surname=EString
		public Assignment getSurnameAssignment_11_1() { return cSurnameAssignment_11_1; }
		
		//EString
		public RuleCall getSurnameEStringParserRuleCall_11_1_0() { return cSurnameEStringParserRuleCall_11_1_0; }
		
		//'userType'
		public Keyword getUserTypeKeyword_12() { return cUserTypeKeyword_12; }
		
		//userType=UserType
		public Assignment getUserTypeAssignment_13() { return cUserTypeAssignment_13; }
		
		//UserType
		public RuleCall getUserTypeUserTypeEnumRuleCall_13_0() { return cUserTypeUserTypeEnumRuleCall_13_0; }
		
		//('solutions' '{' solutions+=Solution* ( "," solutions+=Solution)* '}' )?
		public Group getGroup_14() { return cGroup_14; }
		
		//'solutions'
		public Keyword getSolutionsKeyword_14_0() { return cSolutionsKeyword_14_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_14_1() { return cLeftCurlyBracketKeyword_14_1; }
		
		//solutions+=Solution*
		public Assignment getSolutionsAssignment_14_2() { return cSolutionsAssignment_14_2; }
		
		//Solution
		public RuleCall getSolutionsSolutionParserRuleCall_14_2_0() { return cSolutionsSolutionParserRuleCall_14_2_0; }
		
		//( "," solutions+=Solution)*
		public Group getGroup_14_3() { return cGroup_14_3; }
		
		//","
		public Keyword getCommaKeyword_14_3_0() { return cCommaKeyword_14_3_0; }
		
		//solutions+=Solution
		public Assignment getSolutionsAssignment_14_3_1() { return cSolutionsAssignment_14_3_1; }
		
		//Solution
		public RuleCall getSolutionsSolutionParserRuleCall_14_3_1_0() { return cSolutionsSolutionParserRuleCall_14_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14_4() { return cRightCurlyBracketKeyword_14_4; }
		
		//('problems' '{' problems+=Problem* ( "," problems+=Problem)* '}' )?
		public Group getGroup_15() { return cGroup_15; }
		
		//'problems'
		public Keyword getProblemsKeyword_15_0() { return cProblemsKeyword_15_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_15_1() { return cLeftCurlyBracketKeyword_15_1; }
		
		//problems+=Problem*
		public Assignment getProblemsAssignment_15_2() { return cProblemsAssignment_15_2; }
		
		//Problem
		public RuleCall getProblemsProblemParserRuleCall_15_2_0() { return cProblemsProblemParserRuleCall_15_2_0; }
		
		//( "," problems+=Problem)*
		public Group getGroup_15_3() { return cGroup_15_3; }
		
		//","
		public Keyword getCommaKeyword_15_3_0() { return cCommaKeyword_15_3_0; }
		
		//problems+=Problem
		public Assignment getProblemsAssignment_15_3_1() { return cProblemsAssignment_15_3_1; }
		
		//Problem
		public RuleCall getProblemsProblemParserRuleCall_15_3_1_0() { return cProblemsProblemParserRuleCall_15_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15_4() { return cRightCurlyBracketKeyword_15_4; }
		
		//('itemProcess' '{' itemProcess+=ItemProcess* ( "," itemProcess+=ItemProcess)* '}' )?
		public Group getGroup_16() { return cGroup_16; }
		
		//'itemProcess'
		public Keyword getItemProcessKeyword_16_0() { return cItemProcessKeyword_16_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_16_1() { return cLeftCurlyBracketKeyword_16_1; }
		
		//itemProcess+=ItemProcess*
		public Assignment getItemProcessAssignment_16_2() { return cItemProcessAssignment_16_2; }
		
		//ItemProcess
		public RuleCall getItemProcessItemProcessParserRuleCall_16_2_0() { return cItemProcessItemProcessParserRuleCall_16_2_0; }
		
		//( "," itemProcess+=ItemProcess)*
		public Group getGroup_16_3() { return cGroup_16_3; }
		
		//","
		public Keyword getCommaKeyword_16_3_0() { return cCommaKeyword_16_3_0; }
		
		//itemProcess+=ItemProcess
		public Assignment getItemProcessAssignment_16_3_1() { return cItemProcessAssignment_16_3_1; }
		
		//ItemProcess
		public RuleCall getItemProcessItemProcessParserRuleCall_16_3_1_0() { return cItemProcessItemProcessParserRuleCall_16_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16_4() { return cRightCurlyBracketKeyword_16_4; }
		
		//('process' '{' process+=Process* ( "," process+=Process)* '}' )?
		public Group getGroup_17() { return cGroup_17; }
		
		//'process'
		public Keyword getProcessKeyword_17_0() { return cProcessKeyword_17_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_17_1() { return cLeftCurlyBracketKeyword_17_1; }
		
		//process+=Process*
		public Assignment getProcessAssignment_17_2() { return cProcessAssignment_17_2; }
		
		//Process
		public RuleCall getProcessProcessParserRuleCall_17_2_0() { return cProcessProcessParserRuleCall_17_2_0; }
		
		//( "," process+=Process)*
		public Group getGroup_17_3() { return cGroup_17_3; }
		
		//","
		public Keyword getCommaKeyword_17_3_0() { return cCommaKeyword_17_3_0; }
		
		//process+=Process
		public Assignment getProcessAssignment_17_3_1() { return cProcessAssignment_17_3_1; }
		
		//Process
		public RuleCall getProcessProcessParserRuleCall_17_3_1_0() { return cProcessProcessParserRuleCall_17_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17_4() { return cRightCurlyBracketKeyword_17_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.EDate");
		private final Keyword cEDateKeyword = (Keyword)rule.eContents().get(1);
		
		//EDate returns ecore::EDate:
		//    'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'EDate'
		public Keyword getEDateKeyword() { return cEDateKeyword; }
	}
	public class SolutionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.Solution");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSolutionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAuthorKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAuthorAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cAuthorUserCrossReference_4_1_0 = (CrossReference)cAuthorAssignment_4_1.eContents().get(0);
		private final RuleCall cAuthorUserEStringParserRuleCall_4_1_0_1 = (RuleCall)cAuthorUserCrossReference_4_1_0.eContents().get(1);
		private final Keyword cProblemsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cProblemsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cProblemsProblemCrossReference_7_0 = (CrossReference)cProblemsAssignment_7.eContents().get(0);
		private final RuleCall cProblemsProblemEStringParserRuleCall_7_0_1 = (RuleCall)cProblemsProblemCrossReference_7_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cProblemsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cProblemsProblemCrossReference_8_1_0 = (CrossReference)cProblemsAssignment_8_1.eContents().get(0);
		private final RuleCall cProblemsProblemEStringParserRuleCall_8_1_0_1 = (RuleCall)cProblemsProblemCrossReference_8_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Solution returns Solution:
		//    'Solution'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        ('author' author=[User|EString])?
		//        'problems' '(' problems+=[Problem|EString] ( "," problems+=[Problem|EString])* ')'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Solution'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    ('author' author=[User|EString])?
		//    'problems' '(' problems+=[Problem|EString] ( "," problems+=[Problem|EString])* ')'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Solution'
		public Keyword getSolutionKeyword_0() { return cSolutionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description' description=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//('author' author=[User|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'author'
		public Keyword getAuthorKeyword_4_0() { return cAuthorKeyword_4_0; }
		
		//author=[User|EString]
		public Assignment getAuthorAssignment_4_1() { return cAuthorAssignment_4_1; }
		
		//[User|EString]
		public CrossReference getAuthorUserCrossReference_4_1_0() { return cAuthorUserCrossReference_4_1_0; }
		
		//EString
		public RuleCall getAuthorUserEStringParserRuleCall_4_1_0_1() { return cAuthorUserEStringParserRuleCall_4_1_0_1; }
		
		//'problems'
		public Keyword getProblemsKeyword_5() { return cProblemsKeyword_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6() { return cLeftParenthesisKeyword_6; }
		
		//problems+=[Problem|EString]
		public Assignment getProblemsAssignment_7() { return cProblemsAssignment_7; }
		
		//[Problem|EString]
		public CrossReference getProblemsProblemCrossReference_7_0() { return cProblemsProblemCrossReference_7_0; }
		
		//EString
		public RuleCall getProblemsProblemEStringParserRuleCall_7_0_1() { return cProblemsProblemEStringParserRuleCall_7_0_1; }
		
		//( "," problems+=[Problem|EString])*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//problems+=[Problem|EString]
		public Assignment getProblemsAssignment_8_1() { return cProblemsAssignment_8_1; }
		
		//[Problem|EString]
		public CrossReference getProblemsProblemCrossReference_8_1_0() { return cProblemsProblemCrossReference_8_1_0; }
		
		//EString
		public RuleCall getProblemsProblemEStringParserRuleCall_8_1_0_1() { return cProblemsProblemEStringParserRuleCall_8_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class ProblemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.Problem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProblemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cAuthorKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAuthorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cAuthorUserCrossReference_5_0 = (CrossReference)cAuthorAssignment_5.eContents().get(0);
		private final RuleCall cAuthorUserEStringParserRuleCall_5_0_1 = (RuleCall)cAuthorUserCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSolutionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cSolutionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cSolutionsSolutionCrossReference_6_2_0 = (CrossReference)cSolutionsAssignment_6_2.eContents().get(0);
		private final RuleCall cSolutionsSolutionEStringParserRuleCall_6_2_0_1 = (RuleCall)cSolutionsSolutionCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cSolutionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cSolutionsSolutionCrossReference_6_3_1_0 = (CrossReference)cSolutionsAssignment_6_3_1.eContents().get(0);
		private final RuleCall cSolutionsSolutionEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cSolutionsSolutionCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cProcessKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cProcessAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cProcessItemProcessCrossReference_7_1_0 = (CrossReference)cProcessAssignment_7_1.eContents().get(0);
		private final RuleCall cProcessItemProcessEStringParserRuleCall_7_1_0_1 = (RuleCall)cProcessItemProcessCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Problem returns Problem:
		//    'Problem'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        'author' author=[User|EString]
		//        ('solutions' '(' solutions+=[Solution|EString] ( "," solutions+=[Solution|EString])* ')' )?
		//        ('process' process=[ItemProcess|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Problem'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    'author' author=[User|EString]
		//    ('solutions' '(' solutions+=[Solution|EString] ( "," solutions+=[Solution|EString])* ')' )?
		//    ('process' process=[ItemProcess|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Problem'
		public Keyword getProblemKeyword_0() { return cProblemKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description' description=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//'author'
		public Keyword getAuthorKeyword_4() { return cAuthorKeyword_4; }
		
		//author=[User|EString]
		public Assignment getAuthorAssignment_5() { return cAuthorAssignment_5; }
		
		//[User|EString]
		public CrossReference getAuthorUserCrossReference_5_0() { return cAuthorUserCrossReference_5_0; }
		
		//EString
		public RuleCall getAuthorUserEStringParserRuleCall_5_0_1() { return cAuthorUserEStringParserRuleCall_5_0_1; }
		
		//('solutions' '(' solutions+=[Solution|EString] ( "," solutions+=[Solution|EString])* ')' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'solutions'
		public Keyword getSolutionsKeyword_6_0() { return cSolutionsKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//solutions+=[Solution|EString]
		public Assignment getSolutionsAssignment_6_2() { return cSolutionsAssignment_6_2; }
		
		//[Solution|EString]
		public CrossReference getSolutionsSolutionCrossReference_6_2_0() { return cSolutionsSolutionCrossReference_6_2_0; }
		
		//EString
		public RuleCall getSolutionsSolutionEStringParserRuleCall_6_2_0_1() { return cSolutionsSolutionEStringParserRuleCall_6_2_0_1; }
		
		//( "," solutions+=[Solution|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//solutions+=[Solution|EString]
		public Assignment getSolutionsAssignment_6_3_1() { return cSolutionsAssignment_6_3_1; }
		
		//[Solution|EString]
		public CrossReference getSolutionsSolutionCrossReference_6_3_1_0() { return cSolutionsSolutionCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getSolutionsSolutionEStringParserRuleCall_6_3_1_0_1() { return cSolutionsSolutionEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('process' process=[ItemProcess|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'process'
		public Keyword getProcessKeyword_7_0() { return cProcessKeyword_7_0; }
		
		//process=[ItemProcess|EString]
		public Assignment getProcessAssignment_7_1() { return cProcessAssignment_7_1; }
		
		//[ItemProcess|EString]
		public CrossReference getProcessItemProcessCrossReference_7_1_0() { return cProcessItemProcessCrossReference_7_1_0; }
		
		//EString
		public RuleCall getProcessItemProcessEStringParserRuleCall_7_1_0_1() { return cProcessItemProcessEStringParserRuleCall_7_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ItemProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.ItemProcess");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cItemProcessKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cAuthorKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAuthorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cAuthorUserCrossReference_5_0 = (CrossReference)cAuthorAssignment_5.eContents().get(0);
		private final RuleCall cAuthorUserEStringParserRuleCall_5_0_1 = (RuleCall)cAuthorUserCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cItemProcessTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cItemProcessTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cItemProcessTypeItemSpeciesParserRuleCall_6_1_0 = (RuleCall)cItemProcessTypeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cProblemsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cProblemsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cProblemsProblemParserRuleCall_7_2_0 = (RuleCall)cProblemsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cProblemsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cProblemsProblemParserRuleCall_7_3_1_0 = (RuleCall)cProblemsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ItemProcess returns ItemProcess:
		//    'ItemProcess'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        'author' author=[User|EString]
		//        ('itemProcessType' itemProcessType=ItemSpecies)?
		//        ('problems' '{' problems+=Problem ( "," problems+=Problem)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ItemProcess'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    'author' author=[User|EString]
		//    ('itemProcessType' itemProcessType=ItemSpecies)?
		//    ('problems' '{' problems+=Problem ( "," problems+=Problem)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ItemProcess'
		public Keyword getItemProcessKeyword_0() { return cItemProcessKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description' description=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//'author'
		public Keyword getAuthorKeyword_4() { return cAuthorKeyword_4; }
		
		//author=[User|EString]
		public Assignment getAuthorAssignment_5() { return cAuthorAssignment_5; }
		
		//[User|EString]
		public CrossReference getAuthorUserCrossReference_5_0() { return cAuthorUserCrossReference_5_0; }
		
		//EString
		public RuleCall getAuthorUserEStringParserRuleCall_5_0_1() { return cAuthorUserEStringParserRuleCall_5_0_1; }
		
		//('itemProcessType' itemProcessType=ItemSpecies)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'itemProcessType'
		public Keyword getItemProcessTypeKeyword_6_0() { return cItemProcessTypeKeyword_6_0; }
		
		//itemProcessType=ItemSpecies
		public Assignment getItemProcessTypeAssignment_6_1() { return cItemProcessTypeAssignment_6_1; }
		
		//ItemSpecies
		public RuleCall getItemProcessTypeItemSpeciesParserRuleCall_6_1_0() { return cItemProcessTypeItemSpeciesParserRuleCall_6_1_0; }
		
		//('problems' '{' problems+=Problem ( "," problems+=Problem)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'problems'
		public Keyword getProblemsKeyword_7_0() { return cProblemsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//problems+=Problem
		public Assignment getProblemsAssignment_7_2() { return cProblemsAssignment_7_2; }
		
		//Problem
		public RuleCall getProblemsProblemParserRuleCall_7_2_0() { return cProblemsProblemParserRuleCall_7_2_0; }
		
		//( "," problems+=Problem)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//problems+=Problem
		public Assignment getProblemsAssignment_7_3_1() { return cProblemsAssignment_7_3_1; }
		
		//Problem
		public RuleCall getProblemsProblemParserRuleCall_7_3_1_0() { return cProblemsProblemParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcessKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cStartDateKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStartDateAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStartDateEDateParserRuleCall_5_0 = (RuleCall)cStartDateAssignment_5.eContents().get(0);
		private final Keyword cEndDateKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cEndDateAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cEndDateEDateParserRuleCall_7_0 = (RuleCall)cEndDateAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cStatusKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cStatusAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cStatusProcessStatusEnumRuleCall_8_1_0 = (RuleCall)cStatusAssignment_8_1.eContents().get(0);
		private final Keyword cWeightKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cWeightAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cWeightEDoubleParserRuleCall_10_0 = (RuleCall)cWeightAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cItemProcessKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cItemProcessAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cItemProcessItemProcessCrossReference_11_1_0 = (CrossReference)cItemProcessAssignment_11_1.eContents().get(0);
		private final RuleCall cItemProcessItemProcessEStringParserRuleCall_11_1_0_1 = (RuleCall)cItemProcessItemProcessCrossReference_11_1_0.eContents().get(1);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cLocationKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cLocationAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cLocationLocationParserRuleCall_12_1_0 = (RuleCall)cLocationAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cActionHistoryKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cActionHistoryAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final RuleCall cActionHistoryActionParserRuleCall_13_2_0 = (RuleCall)cActionHistoryAssignment_13_2.eContents().get(0);
		private final Group cGroup_13_3 = (Group)cGroup_13.eContents().get(3);
		private final Keyword cCommaKeyword_13_3_0 = (Keyword)cGroup_13_3.eContents().get(0);
		private final Assignment cActionHistoryAssignment_13_3_1 = (Assignment)cGroup_13_3.eContents().get(1);
		private final RuleCall cActionHistoryActionParserRuleCall_13_3_1_0 = (RuleCall)cActionHistoryAssignment_13_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13_4 = (Keyword)cGroup_13.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Process returns Process:
		//    'Process'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        'startDate' startDate=EDate
		//        'endDate' endDate=EDate
		//        ('status' status=ProcessStatus)?
		//        'weight' weight=EDouble
		//        ('itemProcess' itemProcess=[ItemProcess|EString])?
		//        ('location' location=Location)?
		//        ('actionHistory' '{' actionHistory+=Action ( "," actionHistory+=Action)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Process'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    'startDate' startDate=EDate
		//    'endDate' endDate=EDate
		//    ('status' status=ProcessStatus)?
		//    'weight' weight=EDouble
		//    ('itemProcess' itemProcess=[ItemProcess|EString])?
		//    ('location' location=Location)?
		//    ('actionHistory' '{' actionHistory+=Action ( "," actionHistory+=Action)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Process'
		public Keyword getProcessKeyword_0() { return cProcessKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description' description=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//'startDate'
		public Keyword getStartDateKeyword_4() { return cStartDateKeyword_4; }
		
		//startDate=EDate
		public Assignment getStartDateAssignment_5() { return cStartDateAssignment_5; }
		
		//EDate
		public RuleCall getStartDateEDateParserRuleCall_5_0() { return cStartDateEDateParserRuleCall_5_0; }
		
		//'endDate'
		public Keyword getEndDateKeyword_6() { return cEndDateKeyword_6; }
		
		//endDate=EDate
		public Assignment getEndDateAssignment_7() { return cEndDateAssignment_7; }
		
		//EDate
		public RuleCall getEndDateEDateParserRuleCall_7_0() { return cEndDateEDateParserRuleCall_7_0; }
		
		//('status' status=ProcessStatus)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'status'
		public Keyword getStatusKeyword_8_0() { return cStatusKeyword_8_0; }
		
		//status=ProcessStatus
		public Assignment getStatusAssignment_8_1() { return cStatusAssignment_8_1; }
		
		//ProcessStatus
		public RuleCall getStatusProcessStatusEnumRuleCall_8_1_0() { return cStatusProcessStatusEnumRuleCall_8_1_0; }
		
		//'weight'
		public Keyword getWeightKeyword_9() { return cWeightKeyword_9; }
		
		//weight=EDouble
		public Assignment getWeightAssignment_10() { return cWeightAssignment_10; }
		
		//EDouble
		public RuleCall getWeightEDoubleParserRuleCall_10_0() { return cWeightEDoubleParserRuleCall_10_0; }
		
		//('itemProcess' itemProcess=[ItemProcess|EString])?
		public Group getGroup_11() { return cGroup_11; }
		
		//'itemProcess'
		public Keyword getItemProcessKeyword_11_0() { return cItemProcessKeyword_11_0; }
		
		//itemProcess=[ItemProcess|EString]
		public Assignment getItemProcessAssignment_11_1() { return cItemProcessAssignment_11_1; }
		
		//[ItemProcess|EString]
		public CrossReference getItemProcessItemProcessCrossReference_11_1_0() { return cItemProcessItemProcessCrossReference_11_1_0; }
		
		//EString
		public RuleCall getItemProcessItemProcessEStringParserRuleCall_11_1_0_1() { return cItemProcessItemProcessEStringParserRuleCall_11_1_0_1; }
		
		//('location' location=Location)?
		public Group getGroup_12() { return cGroup_12; }
		
		//'location'
		public Keyword getLocationKeyword_12_0() { return cLocationKeyword_12_0; }
		
		//location=Location
		public Assignment getLocationAssignment_12_1() { return cLocationAssignment_12_1; }
		
		//Location
		public RuleCall getLocationLocationParserRuleCall_12_1_0() { return cLocationLocationParserRuleCall_12_1_0; }
		
		//('actionHistory' '{' actionHistory+=Action ( "," actionHistory+=Action)* '}' )?
		public Group getGroup_13() { return cGroup_13; }
		
		//'actionHistory'
		public Keyword getActionHistoryKeyword_13_0() { return cActionHistoryKeyword_13_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13_1() { return cLeftCurlyBracketKeyword_13_1; }
		
		//actionHistory+=Action
		public Assignment getActionHistoryAssignment_13_2() { return cActionHistoryAssignment_13_2; }
		
		//Action
		public RuleCall getActionHistoryActionParserRuleCall_13_2_0() { return cActionHistoryActionParserRuleCall_13_2_0; }
		
		//( "," actionHistory+=Action)*
		public Group getGroup_13_3() { return cGroup_13_3; }
		
		//","
		public Keyword getCommaKeyword_13_3_0() { return cCommaKeyword_13_3_0; }
		
		//actionHistory+=Action
		public Assignment getActionHistoryAssignment_13_3_1() { return cActionHistoryAssignment_13_3_1; }
		
		//Action
		public RuleCall getActionHistoryActionParserRuleCall_13_3_1_0() { return cActionHistoryActionParserRuleCall_13_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13_4() { return cRightCurlyBracketKeyword_13_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class ItemSpeciesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.ItemSpecies");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cItemSpeciesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cItemSpeciesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ItemSpecies returns ItemSpecies:
		//    {ItemSpecies}
		//    'ItemSpecies'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ItemSpecies}
		//'ItemSpecies'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ItemSpecies}
		public Action getItemSpeciesAction_0() { return cItemSpeciesAction_0; }
		
		//'ItemSpecies'
		public Keyword getItemSpeciesKeyword_1() { return cItemSpeciesKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class LocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.Location");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLocationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLocationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Location returns Location:
		//    {Location}
		//    'Location'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Location}
		//'Location'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Location}
		public Action getLocationAction_0() { return cLocationAction_0; }
		
		//'Location'
		public Keyword getLocationKeyword_1() { return cLocationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cStartDateKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStartDateAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStartDateEDateParserRuleCall_5_0 = (RuleCall)cStartDateAssignment_5.eContents().get(0);
		private final Keyword cEndDateKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cEndDateAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cEndDateEDateParserRuleCall_7_0 = (RuleCall)cEndDateAssignment_7.eContents().get(0);
		private final Keyword cActionsTypeKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cActionsTypeAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cActionsTypeActionTypeEnumRuleCall_9_0 = (RuleCall)cActionsTypeAssignment_9.eContents().get(0);
		private final Keyword cActionStatusKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cActionStatusAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cActionStatusActionStatusEnumRuleCall_11_0 = (RuleCall)cActionStatusAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cProblemKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cProblemAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final CrossReference cProblemProblemCrossReference_12_1_0 = (CrossReference)cProblemAssignment_12_1.eContents().get(0);
		private final RuleCall cProblemProblemEStringParserRuleCall_12_1_0_1 = (RuleCall)cProblemProblemCrossReference_12_1_0.eContents().get(1);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cSolutionKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cSolutionAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final CrossReference cSolutionSolutionCrossReference_13_1_0 = (CrossReference)cSolutionAssignment_13_1.eContents().get(0);
		private final RuleCall cSolutionSolutionEStringParserRuleCall_13_1_0_1 = (RuleCall)cSolutionSolutionCrossReference_13_1_0.eContents().get(1);
		private final Keyword cProcessKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cProcessAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final CrossReference cProcessProcessCrossReference_15_0 = (CrossReference)cProcessAssignment_15.eContents().get(0);
		private final RuleCall cProcessProcessEStringParserRuleCall_15_0_1 = (RuleCall)cProcessProcessCrossReference_15_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//Action returns Action:
		//    'Action'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        'startDate' startDate=EDate
		//        'endDate' endDate=EDate
		//        'actionsType' actionsType=ActionType
		//        'actionStatus' actionStatus=ActionStatus
		//        ('problem' problem=[Problem|EString])?
		//        ('solution' solution=[Solution|EString])?
		//        'process' process=[Process|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Action'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    'startDate' startDate=EDate
		//    'endDate' endDate=EDate
		//    'actionsType' actionsType=ActionType
		//    'actionStatus' actionStatus=ActionStatus
		//    ('problem' problem=[Problem|EString])?
		//    ('solution' solution=[Solution|EString])?
		//    'process' process=[Process|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Action'
		public Keyword getActionKeyword_0() { return cActionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description' description=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//'startDate'
		public Keyword getStartDateKeyword_4() { return cStartDateKeyword_4; }
		
		//startDate=EDate
		public Assignment getStartDateAssignment_5() { return cStartDateAssignment_5; }
		
		//EDate
		public RuleCall getStartDateEDateParserRuleCall_5_0() { return cStartDateEDateParserRuleCall_5_0; }
		
		//'endDate'
		public Keyword getEndDateKeyword_6() { return cEndDateKeyword_6; }
		
		//endDate=EDate
		public Assignment getEndDateAssignment_7() { return cEndDateAssignment_7; }
		
		//EDate
		public RuleCall getEndDateEDateParserRuleCall_7_0() { return cEndDateEDateParserRuleCall_7_0; }
		
		//'actionsType'
		public Keyword getActionsTypeKeyword_8() { return cActionsTypeKeyword_8; }
		
		//actionsType=ActionType
		public Assignment getActionsTypeAssignment_9() { return cActionsTypeAssignment_9; }
		
		//ActionType
		public RuleCall getActionsTypeActionTypeEnumRuleCall_9_0() { return cActionsTypeActionTypeEnumRuleCall_9_0; }
		
		//'actionStatus'
		public Keyword getActionStatusKeyword_10() { return cActionStatusKeyword_10; }
		
		//actionStatus=ActionStatus
		public Assignment getActionStatusAssignment_11() { return cActionStatusAssignment_11; }
		
		//ActionStatus
		public RuleCall getActionStatusActionStatusEnumRuleCall_11_0() { return cActionStatusActionStatusEnumRuleCall_11_0; }
		
		//('problem' problem=[Problem|EString])?
		public Group getGroup_12() { return cGroup_12; }
		
		//'problem'
		public Keyword getProblemKeyword_12_0() { return cProblemKeyword_12_0; }
		
		//problem=[Problem|EString]
		public Assignment getProblemAssignment_12_1() { return cProblemAssignment_12_1; }
		
		//[Problem|EString]
		public CrossReference getProblemProblemCrossReference_12_1_0() { return cProblemProblemCrossReference_12_1_0; }
		
		//EString
		public RuleCall getProblemProblemEStringParserRuleCall_12_1_0_1() { return cProblemProblemEStringParserRuleCall_12_1_0_1; }
		
		//('solution' solution=[Solution|EString])?
		public Group getGroup_13() { return cGroup_13; }
		
		//'solution'
		public Keyword getSolutionKeyword_13_0() { return cSolutionKeyword_13_0; }
		
		//solution=[Solution|EString]
		public Assignment getSolutionAssignment_13_1() { return cSolutionAssignment_13_1; }
		
		//[Solution|EString]
		public CrossReference getSolutionSolutionCrossReference_13_1_0() { return cSolutionSolutionCrossReference_13_1_0; }
		
		//EString
		public RuleCall getSolutionSolutionEStringParserRuleCall_13_1_0_1() { return cSolutionSolutionEStringParserRuleCall_13_1_0_1; }
		
		//'process'
		public Keyword getProcessKeyword_14() { return cProcessKeyword_14; }
		
		//process=[Process|EString]
		public Assignment getProcessAssignment_15() { return cProcessAssignment_15; }
		
		//[Process|EString]
		public CrossReference getProcessProcessCrossReference_15_0() { return cProcessProcessCrossReference_15_0; }
		
		//EString
		public RuleCall getProcessProcessEStringParserRuleCall_15_0_1() { return cProcessProcessEStringParserRuleCall_15_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}
	
	public class UserTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.UserType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cADMINEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cADMINADMINKeyword_0_0 = (Keyword)cADMINEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBASICEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBASICBASICKeyword_1_0 = (Keyword)cBASICEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum UserType returns UserType:
		//                ADMIN = 'ADMIN' | BASIC = 'BASIC';
		public EnumRule getRule() { return rule; }
		
		//ADMIN = 'ADMIN' | BASIC = 'BASIC'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ADMIN = 'ADMIN'
		public EnumLiteralDeclaration getADMINEnumLiteralDeclaration_0() { return cADMINEnumLiteralDeclaration_0; }
		
		//'ADMIN'
		public Keyword getADMINADMINKeyword_0_0() { return cADMINADMINKeyword_0_0; }
		
		//BASIC = 'BASIC'
		public EnumLiteralDeclaration getBASICEnumLiteralDeclaration_1() { return cBASICEnumLiteralDeclaration_1; }
		
		//'BASIC'
		public Keyword getBASICBASICKeyword_1_0() { return cBASICBASICKeyword_1_0; }
	}
	public class ProcessStatusElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.ProcessStatus");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDRAFTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDRAFTDRAFTKeyword_0_0 = (Keyword)cDRAFTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPROGRESSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPROGRESSPROGRESSKeyword_1_0 = (Keyword)cPROGRESSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCOMPLETEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCOMPLETECOMPLETEKeyword_2_0 = (Keyword)cCOMPLETEEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ProcessStatus returns ProcessStatus:
		//                DRAFT = 'DRAFT' | PROGRESS = 'PROGRESS' | COMPLETE = 'COMPLETE';
		public EnumRule getRule() { return rule; }
		
		//DRAFT = 'DRAFT' | PROGRESS = 'PROGRESS' | COMPLETE = 'COMPLETE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DRAFT = 'DRAFT'
		public EnumLiteralDeclaration getDRAFTEnumLiteralDeclaration_0() { return cDRAFTEnumLiteralDeclaration_0; }
		
		//'DRAFT'
		public Keyword getDRAFTDRAFTKeyword_0_0() { return cDRAFTDRAFTKeyword_0_0; }
		
		//PROGRESS = 'PROGRESS'
		public EnumLiteralDeclaration getPROGRESSEnumLiteralDeclaration_1() { return cPROGRESSEnumLiteralDeclaration_1; }
		
		//'PROGRESS'
		public Keyword getPROGRESSPROGRESSKeyword_1_0() { return cPROGRESSPROGRESSKeyword_1_0; }
		
		//COMPLETE = 'COMPLETE'
		public EnumLiteralDeclaration getCOMPLETEEnumLiteralDeclaration_2() { return cCOMPLETEEnumLiteralDeclaration_2; }
		
		//'COMPLETE'
		public Keyword getCOMPLETECOMPLETEKeyword_2_0() { return cCOMPLETECOMPLETEKeyword_2_0; }
	}
	public class ActionTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.ActionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCUSTOMEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCUSTOMCUSTOMKeyword_0_0 = (Keyword)cCUSTOMEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPROBLEMEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPROBLEMPROBLEMKeyword_1_0 = (Keyword)cPROBLEMEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSOLUTIONEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSOLUTIONSOLUTIONKeyword_2_0 = (Keyword)cSOLUTIONEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ActionType returns ActionType:
		//                CUSTOM = 'CUSTOM' | PROBLEM = 'PROBLEM' | SOLUTION = 'SOLUTION';
		public EnumRule getRule() { return rule; }
		
		//CUSTOM = 'CUSTOM' | PROBLEM = 'PROBLEM' | SOLUTION = 'SOLUTION'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CUSTOM = 'CUSTOM'
		public EnumLiteralDeclaration getCUSTOMEnumLiteralDeclaration_0() { return cCUSTOMEnumLiteralDeclaration_0; }
		
		//'CUSTOM'
		public Keyword getCUSTOMCUSTOMKeyword_0_0() { return cCUSTOMCUSTOMKeyword_0_0; }
		
		//PROBLEM = 'PROBLEM'
		public EnumLiteralDeclaration getPROBLEMEnumLiteralDeclaration_1() { return cPROBLEMEnumLiteralDeclaration_1; }
		
		//'PROBLEM'
		public Keyword getPROBLEMPROBLEMKeyword_1_0() { return cPROBLEMPROBLEMKeyword_1_0; }
		
		//SOLUTION = 'SOLUTION'
		public EnumLiteralDeclaration getSOLUTIONEnumLiteralDeclaration_2() { return cSOLUTIONEnumLiteralDeclaration_2; }
		
		//'SOLUTION'
		public Keyword getSOLUTIONSOLUTIONKeyword_2_0() { return cSOLUTIONSOLUTIONKeyword_2_0; }
	}
	public class ActionStatusElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.xtext.Cool.ActionStatus");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTODOEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTODOTODOKeyword_0_0 = (Keyword)cTODOEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPROGRESSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPROGRESSPROGRESSKeyword_1_0 = (Keyword)cPROGRESSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSUCCESSEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSUCCESSSUCCESSKeyword_2_0 = (Keyword)cSUCCESSEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFAILEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFAILFAILKeyword_3_0 = (Keyword)cFAILEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum ActionStatus returns ActionStatus:
		//                TODO = 'TODO' | PROGRESS = 'PROGRESS' | SUCCESS = 'SUCCESS' | FAIL = 'FAIL';
		public EnumRule getRule() { return rule; }
		
		//TODO = 'TODO' | PROGRESS = 'PROGRESS' | SUCCESS = 'SUCCESS' | FAIL = 'FAIL'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TODO = 'TODO'
		public EnumLiteralDeclaration getTODOEnumLiteralDeclaration_0() { return cTODOEnumLiteralDeclaration_0; }
		
		//'TODO'
		public Keyword getTODOTODOKeyword_0_0() { return cTODOTODOKeyword_0_0; }
		
		//PROGRESS = 'PROGRESS'
		public EnumLiteralDeclaration getPROGRESSEnumLiteralDeclaration_1() { return cPROGRESSEnumLiteralDeclaration_1; }
		
		//'PROGRESS'
		public Keyword getPROGRESSPROGRESSKeyword_1_0() { return cPROGRESSPROGRESSKeyword_1_0; }
		
		//SUCCESS = 'SUCCESS'
		public EnumLiteralDeclaration getSUCCESSEnumLiteralDeclaration_2() { return cSUCCESSEnumLiteralDeclaration_2; }
		
		//'SUCCESS'
		public Keyword getSUCCESSSUCCESSKeyword_2_0() { return cSUCCESSSUCCESSKeyword_2_0; }
		
		//FAIL = 'FAIL'
		public EnumLiteralDeclaration getFAILEnumLiteralDeclaration_3() { return cFAILEnumLiteralDeclaration_3; }
		
		//'FAIL'
		public Keyword getFAILFAILKeyword_3_0() { return cFAILFAILKeyword_3_0; }
	}
	
	private final ApplicationElements pApplication;
	private final UserElements pUser;
	private final EStringElements pEString;
	private final EDateElements pEDate;
	private final UserTypeElements eUserType;
	private final SolutionElements pSolution;
	private final ProblemElements pProblem;
	private final ItemProcessElements pItemProcess;
	private final ProcessElements pProcess;
	private final ItemSpeciesElements pItemSpecies;
	private final ProcessStatusElements eProcessStatus;
	private final LocationElements pLocation;
	private final EDoubleElements pEDouble;
	private final ActionElements pAction;
	private final ActionTypeElements eActionType;
	private final ActionStatusElements eActionStatus;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CoolGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pApplication = new ApplicationElements();
		this.pUser = new UserElements();
		this.pEString = new EStringElements();
		this.pEDate = new EDateElements();
		this.eUserType = new UserTypeElements();
		this.pSolution = new SolutionElements();
		this.pProblem = new ProblemElements();
		this.pItemProcess = new ItemProcessElements();
		this.pProcess = new ProcessElements();
		this.pItemSpecies = new ItemSpeciesElements();
		this.eProcessStatus = new ProcessStatusElements();
		this.pLocation = new LocationElements();
		this.pEDouble = new EDoubleElements();
		this.pAction = new ActionElements();
		this.eActionType = new ActionTypeElements();
		this.eActionStatus = new ActionStatusElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("it.disim.univaq.xtext.Cool".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Application returns Application:
	//    'Application'
	//    '{'
	//        'user' '{' user+=User ( "," user+=User)* '}'
	//    '}';
	public ApplicationElements getApplicationAccess() {
		return pApplication;
	}
	
	public ParserRule getApplicationRule() {
		return getApplicationAccess().getRule();
	}
	
	//User returns User:
	//    'User'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        'email' email=EString
	//        'username' username=EString
	//        'uname' uname=EString
	//        ('birthdate' birthdate=EDate)?
	//        ('surname' surname=EString)?
	//        'userType' userType=UserType
	//        ('solutions' '{' solutions+=Solution* ( "," solutions+=Solution)* '}' )?
	//        ('problems' '{' problems+=Problem* ( "," problems+=Problem)* '}' )?
	//        ('itemProcess' '{' itemProcess+=ItemProcess* ( "," itemProcess+=ItemProcess)* '}' )?
	//        ('process' '{' process+=Process* ( "," process+=Process)* '}' )?
	//    '}';
	public UserElements getUserAccess() {
		return pUser;
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EDate returns ecore::EDate:
	//    'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//enum UserType returns UserType:
	//                ADMIN = 'ADMIN' | BASIC = 'BASIC';
	public UserTypeElements getUserTypeAccess() {
		return eUserType;
	}
	
	public EnumRule getUserTypeRule() {
		return getUserTypeAccess().getRule();
	}
	
	//Solution returns Solution:
	//    'Solution'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        ('author' author=[User|EString])?
	//        'problems' '(' problems+=[Problem|EString] ( "," problems+=[Problem|EString])* ')'
	//    '}';
	public SolutionElements getSolutionAccess() {
		return pSolution;
	}
	
	public ParserRule getSolutionRule() {
		return getSolutionAccess().getRule();
	}
	
	//Problem returns Problem:
	//    'Problem'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        'author' author=[User|EString]
	//        ('solutions' '(' solutions+=[Solution|EString] ( "," solutions+=[Solution|EString])* ')' )?
	//        ('process' process=[ItemProcess|EString])?
	//    '}';
	public ProblemElements getProblemAccess() {
		return pProblem;
	}
	
	public ParserRule getProblemRule() {
		return getProblemAccess().getRule();
	}
	
	//ItemProcess returns ItemProcess:
	//    'ItemProcess'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        'author' author=[User|EString]
	//        ('itemProcessType' itemProcessType=ItemSpecies)?
	//        ('problems' '{' problems+=Problem ( "," problems+=Problem)* '}' )?
	//    '}';
	public ItemProcessElements getItemProcessAccess() {
		return pItemProcess;
	}
	
	public ParserRule getItemProcessRule() {
		return getItemProcessAccess().getRule();
	}
	
	//Process returns Process:
	//    'Process'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        'startDate' startDate=EDate
	//        'endDate' endDate=EDate
	//        ('status' status=ProcessStatus)?
	//        'weight' weight=EDouble
	//        ('itemProcess' itemProcess=[ItemProcess|EString])?
	//        ('location' location=Location)?
	//        ('actionHistory' '{' actionHistory+=Action ( "," actionHistory+=Action)* '}' )?
	//    '}';
	public ProcessElements getProcessAccess() {
		return pProcess;
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}
	
	//ItemSpecies returns ItemSpecies:
	//    {ItemSpecies}
	//    'ItemSpecies'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//    '}';
	public ItemSpeciesElements getItemSpeciesAccess() {
		return pItemSpecies;
	}
	
	public ParserRule getItemSpeciesRule() {
		return getItemSpeciesAccess().getRule();
	}
	
	//enum ProcessStatus returns ProcessStatus:
	//                DRAFT = 'DRAFT' | PROGRESS = 'PROGRESS' | COMPLETE = 'COMPLETE';
	public ProcessStatusElements getProcessStatusAccess() {
		return eProcessStatus;
	}
	
	public EnumRule getProcessStatusRule() {
		return getProcessStatusAccess().getRule();
	}
	
	//Location returns Location:
	//    {Location}
	//    'Location'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//    '}';
	public LocationElements getLocationAccess() {
		return pLocation;
	}
	
	public ParserRule getLocationRule() {
		return getLocationAccess().getRule();
	}
	
	//EDouble returns ecore::EDouble:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//Action returns Action:
	//    'Action'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        'startDate' startDate=EDate
	//        'endDate' endDate=EDate
	//        'actionsType' actionsType=ActionType
	//        'actionStatus' actionStatus=ActionStatus
	//        ('problem' problem=[Problem|EString])?
	//        ('solution' solution=[Solution|EString])?
	//        'process' process=[Process|EString]
	//    '}';
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//enum ActionType returns ActionType:
	//                CUSTOM = 'CUSTOM' | PROBLEM = 'PROBLEM' | SOLUTION = 'SOLUTION';
	public ActionTypeElements getActionTypeAccess() {
		return eActionType;
	}
	
	public EnumRule getActionTypeRule() {
		return getActionTypeAccess().getRule();
	}
	
	//enum ActionStatus returns ActionStatus:
	//                TODO = 'TODO' | PROGRESS = 'PROGRESS' | SUCCESS = 'SUCCESS' | FAIL = 'FAIL';
	public ActionStatusElements getActionStatusAccess() {
		return eActionStatus;
	}
	
	public EnumRule getActionStatusRule() {
		return getActionStatusAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
