package ProML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_UserType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_UserType() {
    super(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712842bb0L, "UserType", "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493198256");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ADMIN_0 = new EnumerationDescriptor.MemberDescriptor("ADMIN", "ADMIN", 0x25962a1712842bb1L, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493198257");
  private final EnumerationDescriptor.MemberDescriptor myMember_BASIC_0 = new EnumerationDescriptor.MemberDescriptor("BASIC", "BASIC", 0x25962a1712842bb2L, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493198258");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712842bb0L, 0x25962a1712842bb1L, 0x25962a1712842bb2L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_ADMIN_0, myMember_BASIC_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_BASIC_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ADMIN":
        return myMember_ADMIN_0;
      case "BASIC":
        return myMember_BASIC_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
