package ProML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ActionType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ActionType() {
    super(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d56L, "ActionType", "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493288790");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_PROBLEM_0 = new EnumerationDescriptor.MemberDescriptor("PROBLEM", "PROBLEM", 0x25962a1712858d57L, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493288791");
  private final EnumerationDescriptor.MemberDescriptor myMember_SOLUTION_0 = new EnumerationDescriptor.MemberDescriptor("SOLUTION", "SOLUTION", 0x25962a1712858d58L, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493288792");
  private final EnumerationDescriptor.MemberDescriptor myMember_CUSTOM_0 = new EnumerationDescriptor.MemberDescriptor("CUSTOM", "CUSTOM", 0x25962a1712858d5bL, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493288795");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d56L, 0x25962a1712858d57L, 0x25962a1712858d58L, 0x25962a1712858d5bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_PROBLEM_0, myMember_SOLUTION_0, myMember_CUSTOM_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_CUSTOM_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "PROBLEM":
        return myMember_PROBLEM_0;
      case "SOLUTION":
        return myMember_SOLUTION_0;
      case "CUSTOM":
        return myMember_CUSTOM_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
