package ProML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ProcessStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ProcessStatus() {
    super(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a171285b307L, "ProcessStatus", "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493298439");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_DRAFT_0 = new EnumerationDescriptor.MemberDescriptor("DRAFT", "DRAFT", 0x25962a171285b308L, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493298440");
  private final EnumerationDescriptor.MemberDescriptor myMember_PROGRESS_0 = new EnumerationDescriptor.MemberDescriptor("PROGRESS", "PROGRESS", 0x25962a171285b309L, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493298441");
  private final EnumerationDescriptor.MemberDescriptor myMember_COMPLETED_0 = new EnumerationDescriptor.MemberDescriptor("COMPLETED", "COMPLETED", 0x25962a171285b30cL, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493298444");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a171285b307L, 0x25962a171285b308L, 0x25962a171285b309L, 0x25962a171285b30cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_DRAFT_0, myMember_PROGRESS_0, myMember_COMPLETED_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "DRAFT":
        return myMember_DRAFT_0;
      case "PROGRESS":
        return myMember_PROGRESS_0;
      case "COMPLETED":
        return myMember_COMPLETED_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
