package ProML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ActionStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ActionStatus() {
    super(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d48L, "ActionStatus", "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493288776");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_TODO_0 = new EnumerationDescriptor.MemberDescriptor("TODO", "TODO", 0x25962a1712858d49L, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493288777");
  private final EnumerationDescriptor.MemberDescriptor myMember_PROGRESS_0 = new EnumerationDescriptor.MemberDescriptor("PROGRESS", "PROGRESS", 0x25962a1712858d4aL, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493288778");
  private final EnumerationDescriptor.MemberDescriptor myMember_FAILED_0 = new EnumerationDescriptor.MemberDescriptor("FAILED", "FAILED", 0x25962a1712858d4dL, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493288781");
  private final EnumerationDescriptor.MemberDescriptor myMember_COMPLETED_0 = new EnumerationDescriptor.MemberDescriptor("COMPLETED", "COMPLETED", 0x25962a1712858d51L, "r:e8a1240a-f052-4011-8f7f-dd8a47d16649(ProML.structure)/2708398504493288785");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d48L, 0x25962a1712858d49L, 0x25962a1712858d4aL, 0x25962a1712858d4dL, 0x25962a1712858d51L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_TODO_0, myMember_PROGRESS_0, myMember_FAILED_0, myMember_COMPLETED_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_TODO_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "TODO":
        return myMember_TODO_0;
      case "PROGRESS":
        return myMember_PROGRESS_0;
      case "FAILED":
        return myMember_FAILED_0;
      case "COMPLETED":
        return myMember_COMPLETED_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
