package ProML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int ItemProcess = 1;
  public static final int ItemSpecies = 2;
  public static final int Location = 3;
  public static final int Problem = 4;
  public static final int Process = 5;
  public static final int Solution = 6;
  public static final int User = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x554e933e8e394a86L, 0x9d77357220a3da7cL);
    builder.put(0x25962a1712858d43L, Action);
    builder.put(0x25962a1712858d31L, ItemProcess);
    builder.put(0x25962a1712858d3eL, ItemSpecies);
    builder.put(0x25962a1712858d39L, Location);
    builder.put(0x25962a1712858d2cL, Problem);
    builder.put(0x25962a1712858d34L, Process);
    builder.put(0x25962a1712858d27L, Solution);
    builder.put(0x25962a1712842ba8L, User);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
