package ProML.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Action_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new ItemProcess_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ItemSpecies_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Location_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Problem_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Process_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Solution_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new User_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d43L), MetaIdFactory.conceptId(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d31L), MetaIdFactory.conceptId(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d3eL), MetaIdFactory.conceptId(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d39L), MetaIdFactory.conceptId(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d2cL), MetaIdFactory.conceptId(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d34L), MetaIdFactory.conceptId(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712858d27L), MetaIdFactory.conceptId(0x554e933e8e394a86L, 0x9d77357220a3da7cL, 0x25962a1712842ba8L)).seal();
}
