/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement.serializer;

import com.google.inject.Inject;
import it.disim.univaq.porcessmanagement.Application;
import it.disim.univaq.porcessmanagement.ItemProcess;
import it.disim.univaq.porcessmanagement.ItemSpecies;
import it.disim.univaq.porcessmanagement.Location;
import it.disim.univaq.porcessmanagement.PorcessmanagementPackage;
import it.disim.univaq.porcessmanagement.Problem;
import it.disim.univaq.porcessmanagement.Solution;
import it.disim.univaq.porcessmanagement.User;
import it.disim.univaq.xtext.processmanagement.services.PmanagementGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class PmanagementSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private PmanagementGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == PorcessmanagementPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case PorcessmanagementPackage.ACTION:
				sequence_Action(context, (it.disim.univaq.porcessmanagement.Action) semanticObject); 
				return; 
			case PorcessmanagementPackage.APPLICATION:
				sequence_Application(context, (Application) semanticObject); 
				return; 
			case PorcessmanagementPackage.ITEM_PROCESS:
				sequence_ItemProcess(context, (ItemProcess) semanticObject); 
				return; 
			case PorcessmanagementPackage.ITEM_SPECIES:
				sequence_ItemSpecies(context, (ItemSpecies) semanticObject); 
				return; 
			case PorcessmanagementPackage.LOCATION:
				sequence_Location(context, (Location) semanticObject); 
				return; 
			case PorcessmanagementPackage.PROBLEM:
				sequence_Problem(context, (Problem) semanticObject); 
				return; 
			case PorcessmanagementPackage.PROCESS:
				sequence_Process(context, (it.disim.univaq.porcessmanagement.Process) semanticObject); 
				return; 
			case PorcessmanagementPackage.SOLUTION:
				sequence_Solution(context, (Solution) semanticObject); 
				return; 
			case PorcessmanagementPackage.USER:
				sequence_User(context, (User) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Action returns Action
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         actionsType=ActionType 
	 *         actionStatus=ActionStatus 
	 *         startDate=EString? 
	 *         endDate=EString 
	 *         problem=[Problem|EString]? 
	 *         solution=[Solution|EString]? 
	 *         process=[Process|EString]
	 *     )
	 */
	protected void sequence_Action(ISerializationContext context, it.disim.univaq.porcessmanagement.Action semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Application returns Application
	 *
	 * Constraint:
	 *     (user+=User user+=User*)
	 */
	protected void sequence_Application(ISerializationContext context, Application semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ItemProcess returns ItemProcess
	 *
	 * Constraint:
	 *     (name=EString description=EString? author=[User|EString] itemProcessType=ItemSpecies? (problems+=Problem problems+=Problem*)?)
	 */
	protected void sequence_ItemProcess(ISerializationContext context, ItemProcess semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ItemSpecies returns ItemSpecies
	 *
	 * Constraint:
	 *     (name=EString description=EString?)
	 */
	protected void sequence_ItemSpecies(ISerializationContext context, ItemSpecies semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Location returns Location
	 *
	 * Constraint:
	 *     (name=EString description=EString?)
	 */
	protected void sequence_Location(ISerializationContext context, Location semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Problem returns Problem
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         author=[User|EString] 
	 *         (solutions+=[Solution|EString] solutions+=[Solution|EString]*)? 
	 *         process=[ItemProcess|EString]?
	 *     )
	 */
	protected void sequence_Problem(ISerializationContext context, Problem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Process returns Process
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         status=ProcessStatus? 
	 *         startDate=EString 
	 *         endDate=EString 
	 *         weight=EString 
	 *         itemProcess=[ItemProcess|EString]? 
	 *         location=Location? 
	 *         (actionHistory+=Action actionHistory+=Action*)?
	 *     )
	 */
	protected void sequence_Process(ISerializationContext context, it.disim.univaq.porcessmanagement.Process semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Solution returns Solution
	 *
	 * Constraint:
	 *     (name=EString description=EString? author=[User|EString]? problems+=[Problem|EString] problems+=[Problem|EString]*)
	 */
	protected void sequence_Solution(ISerializationContext context, Solution semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     User returns User
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         email=EString 
	 *         username=EString 
	 *         surname=EString? 
	 *         userType=UserType 
	 *         birthdate=EString? 
	 *         (solutions+=Solution solutions+=Solution*)? 
	 *         (problems+=Problem problems+=Problem*)? 
	 *         (itemProcess+=ItemProcess itemProcess+=ItemProcess*)? 
	 *         (process+=Process process+=Process*)?
	 *     )
	 */
	protected void sequence_User(ISerializationContext context, User semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
