/**
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.cool.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.disim.univaq.xtext.cool.CoolDslRuntimeModule;
import it.disim.univaq.xtext.cool.CoolDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CoolDslIdeSetup extends CoolDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    CoolDslRuntimeModule _coolDslRuntimeModule = new CoolDslRuntimeModule();
    CoolDslIdeModule _coolDslIdeModule = new CoolDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_coolDslRuntimeModule, _coolDslIdeModule));
  }
}
