/**
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.cool.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CoolDslIdeModule extends AbstractCoolDslIdeModule {
}
