/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.cool.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CoolDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/disim/univaq/xtext/cool/parser/antlr/internal/InternalCoolDsl.tokens");
	}
}
