/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.cool.parser.antlr;

import com.google.inject.Inject;
import it.disim.univaq.xtext.cool.parser.antlr.internal.InternalCoolDslParser;
import it.disim.univaq.xtext.cool.services.CoolDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CoolDslParser extends AbstractAntlrParser {

	@Inject
	private CoolDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCoolDslParser createParser(XtextTokenStream stream) {
		return new InternalCoolDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CoolDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CoolDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
