/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.disim.univaq.xtext.CoolRuntimeModule;
import it.disim.univaq.xtext.CoolStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CoolIdeSetup extends CoolStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CoolRuntimeModule(), new CoolIdeModule()));
	}
	
}
