/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import it.disim.univaq.xtext.ide.contentassist.antlr.internal.InternalCoolParser;
import it.disim.univaq.xtext.services.CoolGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class CoolParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CoolGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CoolGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getUserTypeAccess().getAlternatives(), "rule__UserType__Alternatives");
			builder.put(grammarAccess.getProcessStatusAccess().getAlternatives(), "rule__ProcessStatus__Alternatives");
			builder.put(grammarAccess.getActionTypeAccess().getAlternatives(), "rule__ActionType__Alternatives");
			builder.put(grammarAccess.getActionStatusAccess().getAlternatives(), "rule__ActionStatus__Alternatives");
			builder.put(grammarAccess.getApplicationAccess().getGroup(), "rule__Application__Group__0");
			builder.put(grammarAccess.getApplicationAccess().getGroup_5(), "rule__Application__Group_5__0");
			builder.put(grammarAccess.getUserAccess().getGroup(), "rule__User__Group__0");
			builder.put(grammarAccess.getUserAccess().getGroup_3(), "rule__User__Group_3__0");
			builder.put(grammarAccess.getUserAccess().getGroup_10(), "rule__User__Group_10__0");
			builder.put(grammarAccess.getUserAccess().getGroup_11(), "rule__User__Group_11__0");
			builder.put(grammarAccess.getUserAccess().getGroup_14(), "rule__User__Group_14__0");
			builder.put(grammarAccess.getUserAccess().getGroup_14_3(), "rule__User__Group_14_3__0");
			builder.put(grammarAccess.getUserAccess().getGroup_15(), "rule__User__Group_15__0");
			builder.put(grammarAccess.getUserAccess().getGroup_15_3(), "rule__User__Group_15_3__0");
			builder.put(grammarAccess.getUserAccess().getGroup_16(), "rule__User__Group_16__0");
			builder.put(grammarAccess.getUserAccess().getGroup_16_3(), "rule__User__Group_16_3__0");
			builder.put(grammarAccess.getUserAccess().getGroup_17(), "rule__User__Group_17__0");
			builder.put(grammarAccess.getUserAccess().getGroup_17_3(), "rule__User__Group_17_3__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup(), "rule__Solution__Group__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup_3(), "rule__Solution__Group_3__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup_4(), "rule__Solution__Group_4__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup_8(), "rule__Solution__Group_8__0");
			builder.put(grammarAccess.getProblemAccess().getGroup(), "rule__Problem__Group__0");
			builder.put(grammarAccess.getProblemAccess().getGroup_3(), "rule__Problem__Group_3__0");
			builder.put(grammarAccess.getProblemAccess().getGroup_6(), "rule__Problem__Group_6__0");
			builder.put(grammarAccess.getProblemAccess().getGroup_6_3(), "rule__Problem__Group_6_3__0");
			builder.put(grammarAccess.getProblemAccess().getGroup_7(), "rule__Problem__Group_7__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup(), "rule__ItemProcess__Group__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup_3(), "rule__ItemProcess__Group_3__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup_6(), "rule__ItemProcess__Group_6__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup_7(), "rule__ItemProcess__Group_7__0");
			builder.put(grammarAccess.getItemProcessAccess().getGroup_7_3(), "rule__ItemProcess__Group_7_3__0");
			builder.put(grammarAccess.getProcessAccess().getGroup(), "rule__Process__Group__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_3(), "rule__Process__Group_3__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_8(), "rule__Process__Group_8__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_11(), "rule__Process__Group_11__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_12(), "rule__Process__Group_12__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_13(), "rule__Process__Group_13__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_13_3(), "rule__Process__Group_13_3__0");
			builder.put(grammarAccess.getItemSpeciesAccess().getGroup(), "rule__ItemSpecies__Group__0");
			builder.put(grammarAccess.getItemSpeciesAccess().getGroup_4(), "rule__ItemSpecies__Group_4__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getLocationAccess().getGroup_4(), "rule__Location__Group_4__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_3(), "rule__Action__Group_3__0");
			builder.put(grammarAccess.getActionAccess().getGroup_12(), "rule__Action__Group_12__0");
			builder.put(grammarAccess.getActionAccess().getGroup_13(), "rule__Action__Group_13__0");
			builder.put(grammarAccess.getApplicationAccess().getUserAssignment_4(), "rule__Application__UserAssignment_4");
			builder.put(grammarAccess.getApplicationAccess().getUserAssignment_5_1(), "rule__Application__UserAssignment_5_1");
			builder.put(grammarAccess.getUserAccess().getNameAssignment_1(), "rule__User__NameAssignment_1");
			builder.put(grammarAccess.getUserAccess().getDescriptionAssignment_3_1(), "rule__User__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getUserAccess().getEmailAssignment_5(), "rule__User__EmailAssignment_5");
			builder.put(grammarAccess.getUserAccess().getUsernameAssignment_7(), "rule__User__UsernameAssignment_7");
			builder.put(grammarAccess.getUserAccess().getUnameAssignment_9(), "rule__User__UnameAssignment_9");
			builder.put(grammarAccess.getUserAccess().getBirthdateAssignment_10_1(), "rule__User__BirthdateAssignment_10_1");
			builder.put(grammarAccess.getUserAccess().getSurnameAssignment_11_1(), "rule__User__SurnameAssignment_11_1");
			builder.put(grammarAccess.getUserAccess().getUserTypeAssignment_13(), "rule__User__UserTypeAssignment_13");
			builder.put(grammarAccess.getUserAccess().getSolutionsAssignment_14_2(), "rule__User__SolutionsAssignment_14_2");
			builder.put(grammarAccess.getUserAccess().getSolutionsAssignment_14_3_1(), "rule__User__SolutionsAssignment_14_3_1");
			builder.put(grammarAccess.getUserAccess().getProblemsAssignment_15_2(), "rule__User__ProblemsAssignment_15_2");
			builder.put(grammarAccess.getUserAccess().getProblemsAssignment_15_3_1(), "rule__User__ProblemsAssignment_15_3_1");
			builder.put(grammarAccess.getUserAccess().getItemProcessAssignment_16_2(), "rule__User__ItemProcessAssignment_16_2");
			builder.put(grammarAccess.getUserAccess().getItemProcessAssignment_16_3_1(), "rule__User__ItemProcessAssignment_16_3_1");
			builder.put(grammarAccess.getUserAccess().getProcessAssignment_17_2(), "rule__User__ProcessAssignment_17_2");
			builder.put(grammarAccess.getUserAccess().getProcessAssignment_17_3_1(), "rule__User__ProcessAssignment_17_3_1");
			builder.put(grammarAccess.getSolutionAccess().getNameAssignment_1(), "rule__Solution__NameAssignment_1");
			builder.put(grammarAccess.getSolutionAccess().getDescriptionAssignment_3_1(), "rule__Solution__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getSolutionAccess().getAuthorAssignment_4_1(), "rule__Solution__AuthorAssignment_4_1");
			builder.put(grammarAccess.getSolutionAccess().getProblemsAssignment_7(), "rule__Solution__ProblemsAssignment_7");
			builder.put(grammarAccess.getSolutionAccess().getProblemsAssignment_8_1(), "rule__Solution__ProblemsAssignment_8_1");
			builder.put(grammarAccess.getProblemAccess().getNameAssignment_1(), "rule__Problem__NameAssignment_1");
			builder.put(grammarAccess.getProblemAccess().getDescriptionAssignment_3_1(), "rule__Problem__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getProblemAccess().getAuthorAssignment_5(), "rule__Problem__AuthorAssignment_5");
			builder.put(grammarAccess.getProblemAccess().getSolutionsAssignment_6_2(), "rule__Problem__SolutionsAssignment_6_2");
			builder.put(grammarAccess.getProblemAccess().getSolutionsAssignment_6_3_1(), "rule__Problem__SolutionsAssignment_6_3_1");
			builder.put(grammarAccess.getProblemAccess().getProcessAssignment_7_1(), "rule__Problem__ProcessAssignment_7_1");
			builder.put(grammarAccess.getItemProcessAccess().getNameAssignment_1(), "rule__ItemProcess__NameAssignment_1");
			builder.put(grammarAccess.getItemProcessAccess().getDescriptionAssignment_3_1(), "rule__ItemProcess__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getItemProcessAccess().getAuthorAssignment_5(), "rule__ItemProcess__AuthorAssignment_5");
			builder.put(grammarAccess.getItemProcessAccess().getItemProcessTypeAssignment_6_1(), "rule__ItemProcess__ItemProcessTypeAssignment_6_1");
			builder.put(grammarAccess.getItemProcessAccess().getProblemsAssignment_7_2(), "rule__ItemProcess__ProblemsAssignment_7_2");
			builder.put(grammarAccess.getItemProcessAccess().getProblemsAssignment_7_3_1(), "rule__ItemProcess__ProblemsAssignment_7_3_1");
			builder.put(grammarAccess.getProcessAccess().getNameAssignment_1(), "rule__Process__NameAssignment_1");
			builder.put(grammarAccess.getProcessAccess().getDescriptionAssignment_3_1(), "rule__Process__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getProcessAccess().getStartDateAssignment_5(), "rule__Process__StartDateAssignment_5");
			builder.put(grammarAccess.getProcessAccess().getEndDateAssignment_7(), "rule__Process__EndDateAssignment_7");
			builder.put(grammarAccess.getProcessAccess().getStatusAssignment_8_1(), "rule__Process__StatusAssignment_8_1");
			builder.put(grammarAccess.getProcessAccess().getWeightAssignment_10(), "rule__Process__WeightAssignment_10");
			builder.put(grammarAccess.getProcessAccess().getItemProcessAssignment_11_1(), "rule__Process__ItemProcessAssignment_11_1");
			builder.put(grammarAccess.getProcessAccess().getLocationAssignment_12_1(), "rule__Process__LocationAssignment_12_1");
			builder.put(grammarAccess.getProcessAccess().getActionHistoryAssignment_13_2(), "rule__Process__ActionHistoryAssignment_13_2");
			builder.put(grammarAccess.getProcessAccess().getActionHistoryAssignment_13_3_1(), "rule__Process__ActionHistoryAssignment_13_3_1");
			builder.put(grammarAccess.getItemSpeciesAccess().getNameAssignment_2(), "rule__ItemSpecies__NameAssignment_2");
			builder.put(grammarAccess.getItemSpeciesAccess().getDescriptionAssignment_4_1(), "rule__ItemSpecies__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getLocationAccess().getNameAssignment_2(), "rule__Location__NameAssignment_2");
			builder.put(grammarAccess.getLocationAccess().getDescriptionAssignment_4_1(), "rule__Location__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
			builder.put(grammarAccess.getActionAccess().getDescriptionAssignment_3_1(), "rule__Action__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getActionAccess().getStartDateAssignment_5(), "rule__Action__StartDateAssignment_5");
			builder.put(grammarAccess.getActionAccess().getEndDateAssignment_7(), "rule__Action__EndDateAssignment_7");
			builder.put(grammarAccess.getActionAccess().getActionsTypeAssignment_9(), "rule__Action__ActionsTypeAssignment_9");
			builder.put(grammarAccess.getActionAccess().getActionStatusAssignment_11(), "rule__Action__ActionStatusAssignment_11");
			builder.put(grammarAccess.getActionAccess().getProblemAssignment_12_1(), "rule__Action__ProblemAssignment_12_1");
			builder.put(grammarAccess.getActionAccess().getSolutionAssignment_13_1(), "rule__Action__SolutionAssignment_13_1");
			builder.put(grammarAccess.getActionAccess().getProcessAssignment_15(), "rule__Action__ProcessAssignment_15");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CoolGrammarAccess grammarAccess;

	@Override
	protected InternalCoolParser createParser() {
		InternalCoolParser result = new InternalCoolParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CoolGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CoolGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
