/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.xtext.processmanagement.ui.tests;

import com.google.inject.Injector;
import it.disim.univaq.xtext.processmanagement.ui.internal.ProcessmanagementActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PmanagementUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProcessmanagementActivator.getInstance().getInjector("it.disim.univaq.xtext.processmanagement.Pmanagement");
	}

}
